export const styles = {
  shell: "grid min-h-svh bg-canvas text-ink transition-colors duration-300 motion-reduce:transition-none max-[959px]:block min-[960px]:grid-cols-[minmax(0,0.95fr)_minmax(0,1.05fr)]",
  promo: "relative hidden min-h-svh flex-col overflow-hidden bg-[linear-gradient(155deg,#006199,#004773_78%)] p-[clamp(2rem,4vw,4rem)] text-white min-[960px]:flex",
  promoOrbitTop: "pointer-events-none absolute -top-[16%] -right-[26%] aspect-square w-[70%] rounded-full border border-white/15",
  promoOrbitBottom: "pointer-events-none absolute -right-[8%] -bottom-[20%] aspect-square w-[65%] rounded-full border border-white/15",
  promoContent: "relative z-10 my-auto w-full max-w-[560px] py-8",
  promoEyebrow: "text-[.7rem] font-extrabold tracking-[.18em] text-brand-lemon",
  promoTitle: "my-4 max-w-[540px] text-[clamp(3.1rem,4.7vw,5.6rem)] leading-[1.03] font-extrabold tracking-[-.085em]",
  promoDescription: "max-w-[430px] text-base leading-[1.65] text-[#dbf3ff] tiny-height:hidden",
  promoGraphic: "relative mx-auto mt-9 h-[280px] w-[min(380px,86%)] short:mt-4 short:h-[185px] short:w-[min(300px,80%)]",
  promoCard: "absolute top-0 left-[10%] flex h-[255px] w-[245px] -rotate-[7deg] flex-col items-center rounded-[26px] bg-white p-5 text-[#143345] shadow-[0_24px_55px_rgba(0,31,58,.25)] short:h-[175px] short:w-[185px] short:rounded-[20px] short:p-3",
  promoCardLabel: "self-start text-[.62rem] font-extrabold tracking-[.14em] text-[#6f8a98]",
  promoRing: "my-auto grid size-[150px] place-items-center rounded-full bg-[conic-gradient(var(--brand-sun)_0_72%,#e7f3f7_72%_100%)] short:size-[108px]",
  promoRingCenter: "flex size-[113px] flex-col items-center justify-center rounded-full bg-white text-[1.85rem] font-extrabold tracking-[-.06em] short:size-[82px] short:text-[1.35rem]",
  promoRingCaption: "text-[.62rem] font-medium tracking-normal text-[#6f8a98] short:text-[.5rem]",
  promoCardBottom: "flex w-full items-center justify-between text-[.7rem] font-bold short:text-[.6rem]",
  promoFloat: "absolute -right-[4%] bottom-[6%] flex rotate-[5deg] items-center gap-3.5 rounded-2xl bg-brand-lemon px-4 py-3.5 text-[.75rem] font-extrabold text-[#143345] shadow-[0_15px_30px_rgba(0,31,58,.22)] short:right-0 short:bottom-[3%] short:gap-2 short:px-3 short:py-2 short:text-[.65rem]",
  promoFooter: "relative z-10 text-[.66rem] font-extrabold tracking-[.18em] text-[#d2edfb]",
  formSide: "flex min-w-0 flex-col",
  formHeader: "flex items-center justify-end px-[clamp(2rem,5vw,5rem)] py-8 max-[959px]:justify-between max-[959px]:px-[1.35rem] max-[959px]:py-5",
  mobileBrand: "min-[960px]:hidden",
  formContent: "m-auto w-[min(430px,calc(100%-64px))] pt-4 pb-8 max-[959px]:w-[min(430px,calc(100%-44px))] max-[959px]:pt-8 max-[959px]:pb-12 max-[380px]:pt-4",
  eyebrow: "mb-4 text-[.72rem] font-extrabold tracking-[.18em] text-primary",
  title: "text-[clamp(2.7rem,3.6vw,4rem)] leading-[1.08] font-extrabold tracking-[-.075em] max-[959px]:text-[clamp(2.55rem,8vw,3.5rem)] max-[380px]:text-[2.45rem]",
  description: "mt-[1.05rem] mb-[1.9rem] text-[.94rem] leading-[1.65] text-muted max-[380px]:mb-[1.4rem]",
  googleButton: "btn btn-outline min-h-[54px] w-full rounded-[.9rem] border-line bg-surface text-[.89rem] font-bold text-ink transition-colors duration-300 hover:border-primary hover:bg-base-200 hover:text-ink motion-reduce:transition-none",
  switchLink: "font-extrabold text-primary underline underline-offset-[3px]",
  loginEyebrow: "tiny-height:hidden",
  loginPromoTitle: "short:text-[clamp(2.7rem,4vw,4rem)]",
  loginPromoContent: "short:py-0",
  loginFormHeader: "short:py-3",
  loginFormContent: "!py-0",
  loginTitle: "short:text-[clamp(2.15rem,3.2vw,3rem)] tiny-height:text-[2.05rem]",
  loginDescription: "mt-[.85rem] mb-[1.45rem] short:hidden",
  loginGoogle: "short:mt-4 short:min-h-[46px]",
} as const;
